---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: dotnetdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: dotnet
 template:
  metadata:
   name: dotnetpod
   labels:
     app: dotnet	 
  spec: 
    containers:
    - name: dotnetcontainer
      image: chandana320/dotnet:1.0
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: dotnetsvc
spec:
  type: NodePort
  selector:
   app: dotnet
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30222
...