---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: pyflaskdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: pyflask
 template:
  metadata:
   name: pyflaskpod
   labels:
     app: pyflask	 
  spec: 
    containers:
    - name: pyflaskcontainer
      image: chandana320/python-flask:1.0
      ports:
      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
 name: pyflasksvc
spec:
  type: NodePort
  selector:
   app: pyflask
  ports:
   - port: 5000
     targetPort: 5000
     nodePort: 31015
...